apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: my-workflow-argo
spec:
  entrypoint: run-job-and-deployment
  templates:
  - name: run-job
    container:
      image: my-job-image
      command: ["dotnet", "ef", "database", "update"]
      env:
      - name: ConnectionStrings__Default
        value: "host=153.70.79.161,5432; Database =hippo;Persist Security Info=True;User ID=hippo;Password=2k(3Ty}w:+_|0p6]8@IGl=p["
    restartPolicy: OnFailure
  #- name: run-deployment  
  #  containers:
  #  - name:  kubetestapi-deployment
  #    image: ghcr.io/marinosefstathiou/firstimage:v9.9.9
  #    ports:
  #    - containerPort: 80
  #    resources:
  #      requests:
  #	  memory: "200Mi"
  #	  cpu: "1"
  #	limits:
  #	  memory: "200Mi"
  #	  cpu: "1"
  #  imagePullSecrets:
  #    - name: githubsecret
  - name: run-job-and-deployment
    steps:
    - - name: run-job
        template: run-job
      #- name: run-deployment
      #  dependencies: [run-job]
      #  template: run-deployment
