apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetestapi
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes
    repoURL: 'https://github.com/marinosefstathiou/publish-to-grc.git'
    targetRevision: master
  project: default
  syncPolicy:
    automated: null
